#! /bin/sh

# pre-stuff
panel &
compton &
feh --bg-scale /home/w0ne/Pictures/Wallpapers/lit.jpg &
dunst &

notify-send "Welcome home, Master" "What will we be codng today?"

# general
bspc monitor -d      
bspc config border_width            4
bspc config window_gap              30
bspc config top_padding             15
bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true

# colors
bspc config active_border_color         "#000000"
bspc config focused_border_color        "#5f8787"
bspc config presel_border_color         "#181818"
bspc config urgent_border_color         "#C90515"
bspc config focused_locked_border_color "#8c644c"

# misc
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1

